[package]
name = "p9095"
version = "0.1.0"
authors = ["Richie, Jang <richie.jang@kakao.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
